### ISSUE TITLE
LabView executable VI issues

### ISSUE THREAD

**Issue by lucasfrenz** [Fluigent/fgt-SDK#19]
Hi,

I'm experiencing issues when trying to create an executable LabView VI.

The simplest way to reproduce this is to create a LabView project and pull the SDK example VIs into the project. Then create an .exe executable under build.
It won't control the pump and only show an error code (see attached screenshot). On the other hand running the VI regularly within Labview works fine.

The method of creating an executable with the Fluigent SDK worked fine for an older release I tried (1.0.0.13).

I'm using Windows 10 and LabView 2018 32bit.

![Screen Shot 2019-10-01 at 14 07 32](https://user-images.githubusercontent.com/56053225/66009681-62688d80-e470-11e9-901e-37284ab82f04.png)

**Comment by Ygor-Oliveira** [comment]
Hello,

This is due to the fact that there is an indirect dependency on some of the shared libraries, which LabVIEW does not detect, so they are not copied to the build directory. We will try to fix it for the next release. In the mean time, there is an easy workaround:

**1.** Open your project dependencies and locate the fgt_SDK_32.dll item. Right-click on it and select Explore to open its containing folder.


![fgt_sdk_dependencies](https://user-images.githubusercontent.com/53268319/66024139-540f8580-e4f3-11e9-88bd-4d6b7a431fdf.png)

**2.** Select the other 32-bit DLLs in the folder and Drag/drop them in your project. They can be added at the top level or in a virtual folder.


![copy dlls to project](https://user-images.githubusercontent.com/53268319/66024197-7bfee900-e4f3-11e9-9851-8de120cca488.png)
![dlls in project](https://user-images.githubusercontent.com/53268319/66024208-815c3380-e4f3-11e9-8e9d-c4c69b1b8476.png)


**3.** Open your build configuration and, under the Source Files section, select the DLLs you added to your project and add them to Always Included.


![dlls always included](https://user-images.githubusercontent.com/53268319/66024220-891bd800-e4f3-11e9-8fd9-a0b7095a8995.png)

Now, when you build your project, it should copy the necessary files to the data directory of your build output and run correctly.

Let us know if this method works for you.

Best regards,
Ygor

**Comment by lucasfrenz** [comment]
Worked perfectly. Thanks for the quick solution !
