### ISSUE TITLE
Regulation with more than one flow meter fails

### ISSUE THREAD

**Issue by tedstertm** [Fluigent/fgt-SDK#5]
While regulating pressure/flow using a single flow meter things work fine using the SDK. When both flow meters are called to perform regulation using independent pressure regulators regulation fails.

**Comment by CristianGlavana** [comment]
Thank you for the feedback and we are sorry for this desagrement.
Full release is planned next week, beta tests are still going on in order to ensure that there is no major issue. 
Thank you for your contribution, indeed when multiple regulations a bad allocation used same instance insted of separate ones.

You can download the dll fix from master branch.

Please feel free if any question on this SDK and regulation.

**Comment by CristianGlavana** [comment]
Thank you for provided feedback and for participating on beta version. First release 19.0.0 is now available.
This issue will be closed but feel free to contact us for any question.
