### ISSUE TITLE
Oscillating behaviour in the response of our Fluigent LineUp™ series System when using command fgt_set_sensorRegulation()

### ISSUE THREAD

**Issue by kithminrw** [Fluigent/fgt-SDK#75]
Oxygen version: 1.1.0.0
OS: Windows 10 Pro
Device and Firmware Information: [Fluigent.txt](https://github.com/Fluigent/fgt-SDK/files/12834169/Fluigent.txt)

Program command series: 
1. Initiate Fluigent
2. Use a python script with the fgt-SDK
3. fgt_init() and follow the BasicSensorRegulation example
4. Set any flow rate using fgt_set_sensorRegulation() command

Results:
![Fig2_1f](https://github.com/Fluigent/fgt-SDK/assets/25330075/7601f339-6567-4c01-82df-989ddbf484f2)

![Fig2_2_x](https://github.com/Fluigent/fgt-SDK/assets/25330075/9ff2e6e7-a8ff-4fc2-8448-26d0a14d4cc5)

![Fig2_2f_x](https://github.com/Fluigent/fgt-SDK/assets/25330075/a73fb3eb-799c-4a40-aee6-7f7624a5270b)

I need to understand where this oscillatory behavior is coming from. Is it due to the controller?

**Comment by Ygor-Oliveira** [comment]
Hello,

The system can become difficult to control if the fluidic resistance is low compared to the range of your pressure controller, or if there is a significant physical delay between the pressure and the flow rate (e.g., due to long and/or flexible tubing). In these cases, you can use the [fgt_set_sensorRegulationResponse](https://raw.githubusercontent.com/Fluigent/fgt-SDK/23.0.0/Fluigent%20SDK.pdf#subsection.5.2.39) function to increase the response time and force the regulation to take smaller steps, which should mitigate the oscillations.

Best regards,
Ygor

**Comment by mtrellet** [comment]
Hello @kithminrw,

Did Ygor's reply help for your problem? Can I close this issue or do you have other questions?
